<?php

return [
    ['id' => 'أرض', 'name' => Yii::t('app', 'Land')],
    ['id' => 'دور', 'name' => Yii::t('app', 'Floor')],
    ['id' => 'شقة', 'name' => Yii::t('app', 'Apartment')],
    ['id' => 'فيلا', 'name' => Yii::t('app', 'Villa')],
    ['id' => 'شقة صغيرة (استوديو)', 'name' => Yii::t('app', 'Studio Apartment')],
    ['id' => 'غرفة', 'name' => Yii::t('app', 'Room')],
    ['id' => 'استراحة', 'name' => Yii::t('app', 'Chalet')],
    ['id' => 'مجمع', 'name' => Yii::t('app', 'Complex')],
    ['id' => 'برج', 'name' => Yii::t('app', 'Tower')],
    ['id' => 'معرض', 'name' => Yii::t('app', 'Exhibition')],
    ['id' => 'مكتب', 'name' => Yii::t('app', 'Office')],
    ['id' => 'مستودع', 'name' => Yii::t('app', 'Warehouse')],
    ['id' => 'كشك', 'name' => Yii::t('app', 'Kiosk')],
    ['id' => 'سينما', 'name' => Yii::t('app', 'Cinema')],
    ['id' => 'فندق', 'name' => Yii::t('app', 'Hotel')],
    ['id' => 'مواقف سيارات', 'name' => Yii::t('app', 'Parking Lot')],
    ['id' => 'ورشة', 'name' => Yii::t('app', 'Workshop')],
    ['id' => 'صراف', 'name' => Yii::t('app', 'Exchange')],
    ['id' => 'مصنع', 'name' => Yii::t('app', 'Factory')],
    ['id' => 'مدرسة', 'name' => Yii::t('app', 'School')],
    ['id' => 'مستشفى، مركز صحي', 'name' => Yii::t('app', 'Hospital or Health Center')],
    ['id' => 'محطة كهرباء', 'name' => Yii::t('app', 'Power Station')],
    ['id' => 'برج اتصالات', 'name' => Yii::t('app', 'Communication Tower')],
    ['id' => 'محطة', 'name' => Yii::t('app', 'Station')],
    ['id' => 'مزرعة', 'name' => Yii::t('app', 'Farm')],
    ['id' => 'عمارة', 'name' => Yii::t('app', 'Building')],
];